apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetask-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hugoev/k8splayground.git
    targetRevision: main
    path: kubetask-gitops/apps/backend/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kubetask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
