apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetask-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/kubetask-gitops.git
    targetRevision: main
    path: environments/dev/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: kubetask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
