apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubetask-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hugoev/k8splayground.git
    targetRevision: main
    path: kubetask-gitops/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
